create table if not exists source_urls (
    id bigint generated by default as identity primary key,
    source_url text not null,
    resolved_url text,
    source_type text,
    crawl_status text default 'PENDING',
    active_yn char(1) default 'Y',
    memo text,
    last_crawled_at timestamptz,
    last_success_at timestamptz,
    last_failed_at timestamptz,
    last_error_message text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create unique index if not exists uq_source_urls_source_url
    on source_urls (source_url);

create unique index if not exists uq_source_urls_resolved_url
    on source_urls (resolved_url)
    where resolved_url is not null;

create table if not exists crawl_jobs (
    id bigint generated by default as identity primary key,
    source_url_id bigint not null references source_urls(id) on delete cascade,
    job_status text default 'READY',
    started_at timestamptz,
    finished_at timestamptz,
    total_count integer default 0,
    success_count integer default 0,
    failed_count integer default 0,
    error_type text,
    error_message text,
    created_at timestamptz default now()
);

create table if not exists real_estate_listings (
    id bigint generated by default as identity primary key,
    source_url_id bigint references source_urls(id) on delete set null,
    source_type text not null,
    article_no text not null,
    trade_type text,
    property_type text,
    complex_name text,
    building_name text,
    room_info text,
    floor_info text,
    direction text,
    area_m2 numeric,
    exclusive_area_m2 numeric,
    price_text text,
    price_amount bigint,
    deposit_amount bigint,
    monthly_rent_amount bigint,
    realtor_name text,
    confirmed_at text,
    description text,
    source_url text,
    raw_data jsonb,
    first_seen_at timestamptz default now(),
    last_seen_at timestamptz default now(),
    updated_at timestamptz default now(),
    is_active boolean default true,
    constraint uq_real_estate_listing unique (source_type, article_no)
);

create table if not exists real_estate_listing_snapshots (
    id bigint generated by default as identity primary key,
    listing_id bigint references real_estate_listings(id) on delete set null,
    source_url_id bigint references source_urls(id) on delete set null,
    crawl_job_id bigint references crawl_jobs(id) on delete set null,
    source_type text not null,
    article_no text,
    snapshot_data jsonb,
    price_amount bigint,
    deposit_amount bigint,
    monthly_rent_amount bigint,
    collected_at timestamptz default now()
);

create table if not exists crawl_logs (
    id bigint generated by default as identity primary key,
    crawl_job_id bigint references crawl_jobs(id) on delete set null,
    source_url_id bigint references source_urls(id) on delete set null,
    request_url text,
    http_status integer,
    success boolean default false,
    error_type text,
    error_message text,
    requested_at timestamptz default now(),
    elapsed_ms integer
);

create index if not exists ix_source_urls_status_active
    on source_urls (crawl_status, active_yn);

create index if not exists ix_crawl_jobs_source_url_id
    on crawl_jobs (source_url_id);

create index if not exists ix_listings_source_url_id
    on real_estate_listings (source_url_id);

create index if not exists ix_snapshots_article_collected
    on real_estate_listing_snapshots (source_type, article_no, collected_at);

create index if not exists ix_crawl_logs_job_id
    on crawl_logs (crawl_job_id);

create or replace function set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_source_urls_updated_at on source_urls;
create trigger trg_source_urls_updated_at
before update on source_urls
for each row execute function set_updated_at();

drop trigger if exists trg_real_estate_listings_updated_at on real_estate_listings;
create trigger trg_real_estate_listings_updated_at
before update on real_estate_listings
for each row execute function set_updated_at();
